### ISSUE TITLE
Automatic RP tile for the "C" key when moving

### ISSUE THREAD

**Issue by dsshad** [valitas/SGPvP#7]
Hello,

what do you think about the following modification:

When moving around, the (second) last used tile, before one stepped onto the combat tile, is automatically set as RP for the "C" key, if no RP within the visible range is set manually?

A real use case: an enemy pilot got stunned. We went there and killed him. His alliance mate jumped at the same tile to help him out, whom I've been fighting then as well, since I was in a rush and didn't set RP manually before I jumped that tile, I could't retreat using "C" key and died. Main problem was me getting confused with the key and being out of practice, I think, but such a modification could still help to save lifes.

Theoretically it could be done for a much longer distance, so that one can go the whole path back by pressing "C" key to be sure the way back is safe, because one just made that way in the other direction.

**Comment by valitas** [comment]
I don't think this is easy to implement correctly, and I don't have that much time for this, sadly.
